ARDUINO_DIR  = /usr/share/arduino
BOARD_TAG    = mega2560
ARDUINO_PORT = /dev/ttyACM0
USER_LIB_PATH = /home/pi/Submarine-v2/firmware/libraries
ARDUINO_LIBS = EventManager EEPROM

include /usr/share/arduino/Arduino.mk
