CC := gcc
CFLAGS := -Wall
LDFLAGS := -lhiredis_vip -lpthread -lserialport -lminihdlc -llogger -levent

ROOTDIR = $(shell readlink --canonicalize ../..)
SRCDIR = $(CURDIR)/src
BUILDDIR = $(CURDIR)/build

TARGET = $(shell basename $(CURDIR)).c

SOURCES = $(wildcard src/*.c)
SOURCES += $(wildcard $(ROOTDIR)/common/*.c)
OBJECTS = $(patsubst %.c,%.o,$(SOURCES))

LIBDIR = $(ROOTDIR)/libs
LOGGER = $(LIBDIR)/logger
MINIHDLC = $(LIBDIR)/minihdlc
LIBFLAGS = -L$(LOGGER) -L$(MINIHDLC)

INCLUDES = -I$(CURDIR)/src -I$(ROOTDIR)/libs -I$(ROOTDIR)/common

BINDIR = $(ROOTDIR)/bin
TARGET := $(BINDIR)/$(patsubst %.c,%,$(TARGET))

$(info src: $(SOURCES))

default:
	$(CC) $(CFLAGS) $(INCLUDES) $(SOURCES) -o $(TARGET) $(LIBS) $(LIBFLAGS)

#$(TARGET): $(SOURCES)
#	$(CC) -o $@ $(CFLAGS) $(INCLUDES) $^ $(LIBS) $(LIBFLAGS)

#%.o: %.c
#	$(CC) -c -o $@ $(CFLAGS) $(INCLUDES) $< $(LIBS) $(LIBFLAGS)

libs: $(LOGGER) $(MINIHDLC)
	cd $(LOGGER) && make
	cd $(MINIHDLC) && make

clean:
	cd $(BUILDDIR) && rm -f *.o *~