#!/bin/bash

echo uBoot v0.1

if [ "$1" = 1 ]; then
  echo "Bypassing CRC check. Mounting primary."
  mount /dev/mmcblk0p5 /image
  exit 0
fi

crc=`jq '.SBC.image.crc' /configuration/version.json | tr --delete \"`
crc=$(( 16#$crc ))
crc_1=`cksum /dev/mmcblk0p5 | grep -o '^[[:digit:]]*'`

if [ $crc == $crc_1 ];then
  echo "Partiton 1 CRC check passed: $crc_1"
  crc_1_valid=1
else
  echo "Partiton 1 CRC check failed: $crc_1"
  crc_1_valid=0
fi

crc_2=`cksum /dev/mmcblk0p6 | grep -o '^[[:digit:]]*'`

if [ $crc == $crc_2 ];then
  echo "Partiton 2 CRC check passed: $crc_2"
  crc_2_valid=1
else
  echo "Partiton 2 CRC check failed: $crc_2"
  crc_2_valid=0
fi

if [[ "$crc_1_valid" -eq 1 && "$crc_2_valid" -eq 0 ]] ; then
  echo "Copying partition 1 to partition 2"
  dd if=/dev/mmcblk0p5 of=/dev/mmcblk0p6
fi

if [ "$crc_1_valid" -eq 1 ]; then
  echo "Mounting partition 1"
  mount /dev/mmcblk0p5 /image
elif [ "$crc_2_valid" -eq 1 ]; then
  echo "Mounting partition 2"
  mount /dev/mmcblk0p6 /image
fi

#/image/application/bootsequence.py
